data:
  evfile : ft11.txt
  scfile : ft12.txt

binning:
  roiwidth   : 15.0
  binsz      : 0.1
  binsperdec : 3

selection :
  emin : 100
  emax : 1500000
  zmax    : 90
  evtype  : 3
  tmin    : 418003203
  tmax    : 433814403
  filter  : null
  target : 'mkn501'

gtlike:
  edisp : True
  irfs : 'P8R3_SOURCE_V3'
  edisp_disable : ['isodiff','galdiff']

model:
  src_roiwidth : 15.0
  galdiff  : 'gll_iem_v07.fits'
  isodiff  : 'iso_P8R3_SOURCE_V3_v1.txt'
  catalogs : 
    - '4FGL'
